// <auto-generated />
using AutoOglasi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AutoOglasi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("AutoOglasi.Models.Automobil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Cena")
                        .HasColumnType("TEXT");

                    b.Property<int>("Godiste")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Gorivo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Karoserija")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kontakt")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Marka")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Opis")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Snaga")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ZapreminaMotora")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Automobili");
                });
#pragma warning restore 612, 618
        }
    }
}
